#ifndef __ERROR_H__
#define __ERROR_H__

#define SUCCESS 0

#define ERROR_ADD_FIELD_MALLOC 0x01
#define ERROR_NO_HOST_FIELD 0x02
#define ERROR_REQUEST_LINE 0x03
#define ERROR_MALLOC_FAIL 0x04
#define ERROR_RESPONSE_LINE 0x05
#define ERROR_ADD_CACHE_OVERSIZE 0x06
#define ERROR_CACHE_FIND_NOTHING 0x07
#define ERROR_BUFF_TOO_SMALL 0x08

#endif